import js from '@eslint/js';
import noUnsanitized from 'eslint-plugin-no-unsanitized';

export default [
  js.configs.recommended,
  noUnsanitized.configs.recommended,
  {
    files: ['components/**/*.js', 'patterns/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        customElements: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        queueMicrotask: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        history: 'readonly',
        location: 'readonly',
        navigator: 'readonly',
        performance: 'readonly',
        getComputedStyle: 'readonly',
        console: 'readonly',
        CSS: 'readonly',
        CSSStyleSheet: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        KeyboardEvent: 'readonly',
        MouseEvent: 'readonly',
        FocusEvent: 'readonly',
        Node: 'readonly',
        NodeList: 'readonly',
        Element: 'readonly',
        PopoverInvokerElement: 'readonly',
        htmx: 'readonly',
        DOMParser: 'readonly',
        AbortController: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': 'warn',
      'prefer-const': 'error',
      'no-var': 'error',
      'no-empty': 'warn',
      'no-useless-assignment': 'warn',
    },
  },
  {
    ignores: ['catalog/**', 'node_modules/**', 'custom-elements.json'],
  },
];
